BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[GDA_BASKET_INDICATOR] DROP CONSTRAINT [GDA_BASKET_INDICATOR_SECTOR_ID_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] DROP CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_SECTOR_IDGDA_SECTOR_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] DROP CONSTRAINT [GDA_CONSOLIDATED_RESULTS_sectorId_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] DROP CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_sector_id_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] DROP CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_sector_id_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] DROP CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_SECTOR_fkey];

-- RedefineTables
BEGIN TRANSACTION;
DECLARE @SQL NVARCHAR(MAX) = N''
SELECT @SQL += N'ALTER TABLE '
    + QUOTENAME(OBJECT_SCHEMA_NAME(PARENT_OBJECT_ID))
    + '.'
    + QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID))
    + ' DROP CONSTRAINT '
    + OBJECT_NAME(OBJECT_ID) + ';'
FROM SYS.OBJECTS
WHERE TYPE_DESC LIKE '%CONSTRAINT'
    AND OBJECT_NAME(PARENT_OBJECT_ID) = 'GDA_SECTOR'
    AND SCHEMA_NAME(SCHEMA_ID) = 'dbo'
EXEC sp_executesql @SQL
;
CREATE TABLE [dbo].[_prisma_new_GDA_SECTOR] (
    [IDGDA_SECTOR] INT NOT NULL,
    [NAME] NVARCHAR(1000) NOT NULL,
    [LEVEL] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_SECTOR_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_SECTOR_pkey] PRIMARY KEY CLUSTERED ([IDGDA_SECTOR])
);
IF EXISTS(SELECT * FROM [dbo].[GDA_SECTOR])
    EXEC('INSERT INTO [dbo].[_prisma_new_GDA_SECTOR] ([CREATED_AT],[DELETED_AT],[IDGDA_SECTOR],[LEVEL],[NAME]) SELECT [CREATED_AT],[DELETED_AT],[IDGDA_SECTOR],[LEVEL],[NAME] FROM [dbo].[GDA_SECTOR] WITH (holdlock tablockx)');
DROP TABLE [dbo].[GDA_SECTOR];
EXEC SP_RENAME N'dbo._prisma_new_GDA_SECTOR', N'GDA_SECTOR';
COMMIT;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_BASKET_INDICATOR] ADD CONSTRAINT [GDA_BASKET_INDICATOR_SECTOR_ID_fkey] FOREIGN KEY ([SECTOR_ID]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_sectorId_fkey] FOREIGN KEY ([sectorId]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_SECTOR_IDGDA_SECTOR_fkey] FOREIGN KEY ([GDA_SECTOR_IDGDA_SECTOR]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_sector_id_fkey] FOREIGN KEY ([sector_id]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_sector_id_fkey] FOREIGN KEY ([sector_id]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_SECTOR_fkey] FOREIGN KEY ([IDGDA_SECTOR]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
