BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[GDA_ATRIBUTES] (
    [IDGDA_ATRIBUTES] INT NOT NULL IDENTITY(1,1),
    [IDGDA_COLLABORATORS] INT,
    [NAME] NVARCHAR(max),
    [LEVEL] INT NOT NULL,
    [VALUE] NVARCHAR(max),
    [CREATED_AT] DATETIME,
    CONSTRAINT [PK_dbo.GDA_ATRIBUTES] PRIMARY KEY CLUSTERED ([IDGDA_ATRIBUTES])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_CHECKING_ACCOUNT] (
    [id] INT NOT NULL IDENTITY(1,1),
    [input] FLOAT(53),
    [output] FLOAT(53),
    [balance] FLOAT(53) NOT NULL CONSTRAINT [GDA_CHECKING_ACCOUNT_balance_df] DEFAULT 0,
    [collaborator_id] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_CHECKING_ACCOUNT_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [GDA_INDICATOR_IDGDA_INDICATOR] INT,
    [GDA_ORDER_IDGDA_ORDER] INT,
    CONSTRAINT [GDA_CHECKING_ACCOUNT_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_COLLABORATOR_VOUCHER] (
    [IDGDA_COLLABORATOR_VOUCHER] INT NOT NULL IDENTITY(1,1),
    [collaboratorId] INT NOT NULL,
    [voucherId] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_COLLABORATOR_VOUCHER_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_COLLABORATOR_VOUCHER_pkey] PRIMARY KEY CLUSTERED ([IDGDA_COLLABORATOR_VOUCHER])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_COLLABORATORS] (
    [IDGDA_COLLABORATORS] INT NOT NULL IDENTITY(1,1),
    [NAME] NVARCHAR(1000) NOT NULL,
    [COLLABORATORIDENTIFICATION] NVARCHAR(1000) NOT NULL,
    [MATRICULA] NVARCHAR(1000) NOT NULL,
    [GENRE] NVARCHAR(1000) NOT NULL,
    [BIRTHDATE] DATETIME2 NOT NULL,
    [ADMISSIONDATE] DATETIME2 NOT NULL,
    [CIVILSTATE] INT NOT NULL,
    [ACTIVE] NVARCHAR(1000),
    [EMAIL] NVARCHAR(1000),
    [STREET] NVARCHAR(1000),
    [NUMBER] INT,
    [NEIGHBORHOOD] NVARCHAR(1000),
    [CITY] NVARCHAR(1000),
    [STATE] NVARCHAR(1000),
    [COUNTRY] NVARCHAR(1000),
    [HOMENUMBER] NVARCHAR(1000),
    [PHONENUMBER] NVARCHAR(1000),
    [SCHOOLING] INT,
    [CONTRACTORCONTROLID] NVARCHAR(1000),
    [DEPENDANTNUMBER] NVARCHAR(1000),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_COLLABORATORS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [UPDATED_AT] DATETIME2,
    [TRANSACTIONID] BIGINT,
    [ENTRYDATE] DATETIME2,
    [ENTRY_TIME] TIME,
    [HOME_BASED] BIT,
    CONSTRAINT [GDA_COLLABORATORS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_COLLABORATORS])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_CONFIG] (
    [IDGDA_CONFIG] INT NOT NULL IDENTITY(1,1),
    [NAME] NVARCHAR(max),
    [VALUE] NVARCHAR(max),
    CONSTRAINT [PK_dbo.GDA_CONFIG] PRIMARY KEY CLUSTERED ([IDGDA_CONFIG])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [resultId] INT,
    [sectorId] INT,
    [value] FLOAT(53) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_CONSOLIDATED_RESULTS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [collaboratorId] INT,
    [goal] FLOAT(53),
    [indicatorId] INT,
    [transactionId] INT,
    CONSTRAINT [GDA_CONSOLIDATED_RESULTS_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_USERS] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Login] NVARCHAR(1000) NOT NULL,
    [Senha] NVARCHAR(1000) NOT NULL,
    [collaborator_id] INT,
    CONSTRAINT [GDA_USERS_pkey] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [GDA_USERS_Login_key] UNIQUE NONCLUSTERED ([Login])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_FACTOR] (
    [IDGDA_FACTOR] INT NOT NULL IDENTITY(1,1),
    [index] INT NOT NULL,
    [factor] FLOAT(53) NOT NULL,
    [IDGDA_RESULT] INT NOT NULL,
    CONSTRAINT [GDA_FACTOR_pkey] PRIMARY KEY CLUSTERED ([IDGDA_FACTOR])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] (
    [id] INT NOT NULL IDENTITY(1,1),
    [monetization] FLOAT(53),
    [GDA_CHECKING_ACCOUNT_IDGDA_CHECKING_ACCOUNT] INT NOT NULL,
    [GDA_HIERARCHY_IDGDA_HIERARCHY] INT,
    [GDA_INDICATOR_IDGDA_INDICATOR] INT NOT NULL,
    [GDA_SECTOR_IDGDA_SECTOR] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2 CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_DELETED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] (
    [IDGDA_HISTORY_STOCK_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [AMOUNT_INPUT] FLOAT(53),
    [AMOUNT_OUTPUT] FLOAT(53),
    [EXPIRATION_DATE] DATETIME2,
    [REGISTERED_BY] INT NOT NULL,
    [GDA_PRODUCT_IDGDA_PRODUCT] INT NOT NULL,
    [GDA_STOCK_IDGDA_STOCK] INT NOT NULL,
    [GDA_REASON_REMOVED_IDGDA_REASON_REMOVED] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HISTORY_STOCK_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_MKT_CONFIG] (
    [IDGDA_MKT_CONFIG] INT NOT NULL IDENTITY(1,1),
    [TYPE] NVARCHAR(1000) NOT NULL,
    [VALUE] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_MKT_CONFIG_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_MKT_CONFIG_pkey] PRIMARY KEY CLUSTERED ([IDGDA_MKT_CONFIG])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_ORDER_PRODUCT] (
    [IDGDA_ORDER_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [AMOUNT] INT NOT NULL,
    [PRICE] FLOAT(53) NOT NULL CONSTRAINT [GDA_ORDER_PRODUCT_PRICE_df] DEFAULT 0,
    [GDA_ORDER_IDGDA_ORDER] INT NOT NULL,
    [GDA_PRODUCT_IDGDA_PRODUCT] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_ORDER_PRODUCT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_ORDER_PRODUCT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_ORDER_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_ORDER_STATUS] (
    [IDGDA_ORDER_STATUS] INT NOT NULL IDENTITY(1,1),
    [STATUS] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_ORDER_STATUS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_ORDER_STATUS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_ORDER_STATUS])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_ORDER] (
    [IDGDA_ORDER] INT NOT NULL IDENTITY(1,1),
    [ORDER_BY] INT NOT NULL,
    [DELIVERED_BY] INT,
    [GDA_ORDER_STATUS_IDGDA_ORDER_STATUS] INT NOT NULL,
    [GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_ORDER_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [COD_ORDER] NVARCHAR(1000),
    [DELIVERED_AT] DATETIME2,
    [DUE_AT] DATETIME2,
    [OBSERVATION_DELIVERED] NVARCHAR(1000),
    [OBSERVATION_ORDER] NVARCHAR(1000),
    [ORDER_AT] DATETIME2,
    [RELEASED_AT] DATETIME2,
    [RELEASED_BY] INT,
    [TOTAL_PRICE] FLOAT(53) NOT NULL CONSTRAINT [GDA_ORDER_TOTAL_PRICE_df] DEFAULT 0,
    CONSTRAINT [GDA_ORDER_pkey] PRIMARY KEY CLUSTERED ([IDGDA_ORDER])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PRODUCT] (
    [IDGDA_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [DESCRIPTION] NVARCHAR(1000) NOT NULL,
    [CODE] NVARCHAR(1000) NOT NULL,
    [REGISTERED_BY] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_PRODUCT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [price] FLOAT(53) NOT NULL,
    [type] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_PRODUCT_type_df] DEFAULT 'PHYSICAL',
    CONSTRAINT [GDA_PRODUCT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_REASON_REMOVED] (
    [IDGDA_REASON_REMOVED] INT NOT NULL IDENTITY(1,1),
    [REASON] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_REASON_REMOVED_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_REASON_REMOVED_pkey] PRIMARY KEY CLUSTERED ([IDGDA_REASON_REMOVED])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_STOCK_PRODUCT] (
    [IDGDA_STOCK_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [AMOUNT] FLOAT(53),
    [EXPIRATION_DATE] DATETIME2,
    [REGISTERED_BY] INT NOT NULL,
    [GDA_PRODUCT_IDGDA_PRODUCT] INT NOT NULL,
    [GDA_STOCK_IDGDA_STOCK] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_STOCK_PRODUCT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [autosale] BIT NOT NULL CONSTRAINT [GDA_STOCK_PRODUCT_autosale_df] DEFAULT 0,
    CONSTRAINT [GDA_STOCK_PRODUCT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_STOCK_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_STOCK] (
    [IDGDA_STOCK] INT NOT NULL IDENTITY(1,1),
    [DESCRIPTION] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_STOCK_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [CITY] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_STOCK_CITY_df] DEFAULT '',
    CONSTRAINT [GDA_STOCK_pkey] PRIMARY KEY CLUSTERED ([IDGDA_STOCK])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_GROUPS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000) NOT NULL,
    [alias] NVARCHAR(1000) NOT NULL,
    [uploadId] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_GROUPS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_GROUPS_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [GDA_GROUPS_alias_key] UNIQUE NONCLUSTERED ([alias])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HIERARCHY] (
    [IDGDA_HIERARCHY] INT NOT NULL IDENTITY(1,1),
    [LEVELNAME] NVARCHAR(1000) NOT NULL,
    [LEVELWEIGHT] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HIERARCHY_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_HIERARCHY_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HIERARCHY])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_COLLABORATOR_SECTOR] (
    [IDGDA_HISTORY_COLLABORATOR_SECTOR] INT NOT NULL IDENTITY(1,1),
    [CREATED_AT] DATETIME,
    [IDGDA_COLLABORATORS] INT,
    [IDGDA_SECTOR] INT,
    [TRANSACTIONID] INT,
    CONSTRAINT [PK_GDA_HISTORY_COLLABORATOR_SECTOR] PRIMARY KEY CLUSTERED ([IDGDA_HISTORY_COLLABORATOR_SECTOR])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_HIERARCHY_RELATIONSHIP] (
    [IDGDA_HISTORY_HIERARCHY_RELATIONSHIP] INT NOT NULL IDENTITY(1,1),
    [CONTRACTORCONTROLID] INT NOT NULL,
    [PARENTIDENTIFICATION] INT,
    [IDGDA_COLLABORATORS] INT NOT NULL,
    [IDGDA_HIERARCHY] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_HIERARCHY_RELATIONSHIP_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [TRANSACTIONID] INT,
    [LEVELWEIGHT] INT,
    [DATE] DATETIME2,
    [LEVELNAME] NVARCHAR(max),
    CONSTRAINT [GDA_HISTORY_HIERARCHY_RELATIONSHIP_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HISTORY_HIERARCHY_RELATIONSHIP])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] (
    [id] INT NOT NULL IDENTITY(1,1),
    [indicator_id] INT NOT NULL,
    [sector_id] INT NOT NULL,
    [metric_min] FLOAT(53) NOT NULL,
    [metric_max] FLOAT(53) NOT NULL,
    [monetization] INT,
    [groupId] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [indicator_id] INT NOT NULL,
    [sector_id] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    [goal] FLOAT(53) NOT NULL,
    [ACTIVE] BIT,
    [ALTERED_BY] INT,
    [ENDED_AT] DATETIME2,
    [STARTED_AT] DATETIME2,
    CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_sector_id_indicator_id_created_at_key] UNIQUE NONCLUSTERED ([sector_id],[indicator_id],[created_at])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_INDICATOR] (
    [IDGDA_INDICATOR] INT NOT NULL IDENTITY(1,1),
    [NAME] NVARCHAR(1000) NOT NULL,
    [DESCRIPTION] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_INDICATOR_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_INDICATOR_pkey] PRIMARY KEY CLUSTERED ([IDGDA_INDICATOR])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_LOGREQUEST] (
    [IDGDA_LOGREQUEST] INT NOT NULL IDENTITY(1,1),
    [REQUEST] NVARCHAR(max),
    [ROUTE] NVARCHAR(200) NOT NULL,
    [RETURN] INT NOT NULL,
    CONSTRAINT [PK_dbo.GDA_LOGREQUEST] PRIMARY KEY CLUSTERED ([IDGDA_LOGREQUEST])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_MATHEMATICAL_EXPRESSIONS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [expression] NVARCHAR(1000) NOT NULL,
    [indicatorId] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_MATHEMATICAL_EXPRESSIONS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_MATHEMATICAL_EXPRESSIONS_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PERMISSIONS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [action] NVARCHAR(1000) NOT NULL,
    [resource] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_PERMISSIONS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_PERMISSIONS_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PRODUCT_IMAGES] (
    [IDGDA_HISTORY_STOCK_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [uploadId] INT NOT NULL,
    [productId] INT NOT NULL,
    CONSTRAINT [GDA_PRODUCT_IMAGES_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HISTORY_STOCK_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PRODUCTS] (
    [IDGDA_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [description] NVARCHAR(1000) NOT NULL,
    [code] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_PRODUCTS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    [collaboratorId] INT NOT NULL,
    [price] FLOAT(53) NOT NULL,
    CONSTRAINT [GDA_PRODUCTS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PROFILE_PERMISSIONS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [permission_id] INT NOT NULL,
    [profile_id] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_PROFILE_PERMISSIONS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_PROFILE_PERMISSIONS_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PROFILES] (
    [id] INT NOT NULL IDENTITY(1,1),
    [profile] NVARCHAR(1000) NOT NULL,
    [level] INT NOT NULL,
    [hierarchy_id] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_PRFILES_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_PRFILES_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_RESULT] (
    [IDGDA_RESULT] INT NOT NULL IDENTITY(1,1),
    [INDICADORID] INT,
    [TRANSACTIONID] INT,
    [RESULT] FLOAT(53),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_RESULT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [IDGDA_COLLABORATORS] INT,
    [factors] NVARCHAR(1000),
    CONSTRAINT [GDA_RESULT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_RESULT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_SECTOR] (
    [IDGDA_SECTOR] INT NOT NULL IDENTITY(1,1),
    [NAME] NVARCHAR(1000) NOT NULL,
    [LEVEL] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_SECTOR_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_SECTOR_pkey] PRIMARY KEY CLUSTERED ([IDGDA_SECTOR])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_SHOPPING_CART] (
    [IDGDA_SHOPPINGCART] INT NOT NULL IDENTITY(1,1),
    [ORDER_BY] INT NOT NULL,
    [AMOUNT] INT NOT NULL,
    [STOCK_PRODUCT_ID] INT NOT NULL,
    CONSTRAINT [GDA_SHOPPING_CART_pkey] PRIMARY KEY CLUSTERED ([IDGDA_SHOPPINGCART])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_TOKEN] (
    [IDGDA_TOKEN] INT NOT NULL IDENTITY(1,1),
    [TOKEN] NVARCHAR(max),
    [ACTIVE] INT NOT NULL,
    CONSTRAINT [PK_dbo.GDA_TOKEN] PRIMARY KEY CLUSTERED ([IDGDA_TOKEN])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_TRANSACTION] (
    [IDGDA_TRANSACTION] INT NOT NULL IDENTITY(1,1),
    [TRANSACTIONID] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_TRANSACTION_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2,
    [COMPLETE] BIT NOT NULL,
    [STATUS] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_TRANSACTION_STATUS_df] DEFAULT 'READY',
    CONSTRAINT [GDA_TRANSACTION_pkey] PRIMARY KEY CLUSTERED ([IDGDA_TRANSACTION])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_UPLOADS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [originalName] NVARCHAR(1000) NOT NULL,
    [key] NVARCHAR(1000) NOT NULL,
    [type] NVARCHAR(1000) NOT NULL,
    [url] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_UPLOADS_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_UPLOADS_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [GDA_UPLOADS_key_key] UNIQUE NONCLUSTERED ([key])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_VISIBILITY] (
    [IDGDA_VISIBILITY] INT NOT NULL IDENTITY(1,1),
    [TYPE] NVARCHAR(1000) NOT NULL,
    [VALUE] NVARCHAR(1000) NOT NULL,
    [GDA_PRODUCT_IDGDA_PRODUCT_ID] INT NOT NULL,
    CONSTRAINT [GDA_VISIBILITY_pkey] PRIMARY KEY CLUSTERED ([IDGDA_VISIBILITY])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_VOUCHERS] (
    [IDGDA_VOUCHERS] INT NOT NULL IDENTITY(1,1),
    [productId] INT NOT NULL,
    [voucher] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_VOUCHERS_status_df] DEFAULT 'AVAILABLE',
    CONSTRAINT [GDA_VOUCHERS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_VOUCHERS])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [GDA_CONSOLIDATED_RESULTS_collaboratorId_transactionId_indicatorId_idx] ON [dbo].[GDA_CONSOLIDATED_RESULTS]([collaboratorId], [transactionId], [indicatorId]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [GDA_HISTORY_HIERARCHY_RELATIONSHIP_IDGDA_COLLABORATORS_IDGDA_HIERARCHY_idx] ON [dbo].[GDA_HISTORY_HIERARCHY_RELATIONSHIP]([IDGDA_COLLABORATORS], [IDGDA_HIERARCHY]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [GDA_RESULT_IDGDA_COLLABORATORS_TRANSACTIONID_INDICADORID_idx] ON [dbo].[GDA_RESULT]([IDGDA_COLLABORATORS], [TRANSACTIONID], [INDICADORID]);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_collaborator_id_fkey] FOREIGN KEY ([collaborator_id]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_INDICATOR_IDGDA_INDICATOR_fkey] FOREIGN KEY ([GDA_INDICATOR_IDGDA_INDICATOR]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_ORDER_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_ORDER_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_COLLABORATOR_VOUCHER] ADD CONSTRAINT [GDA_COLLABORATOR_VOUCHER_collaboratorId_fkey] FOREIGN KEY ([collaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_COLLABORATOR_VOUCHER] ADD CONSTRAINT [GDA_COLLABORATOR_VOUCHER_voucherId_fkey] FOREIGN KEY ([voucherId]) REFERENCES [dbo].[GDA_VOUCHERS]([IDGDA_VOUCHERS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_collaboratorId_fkey] FOREIGN KEY ([collaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_indicatorId_fkey] FOREIGN KEY ([indicatorId]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_resultId_fkey] FOREIGN KEY ([resultId]) REFERENCES [dbo].[GDA_RESULT]([IDGDA_RESULT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_sectorId_fkey] FOREIGN KEY ([sectorId]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATED_RESULTS] ADD CONSTRAINT [GDA_CONSOLIDATED_RESULTS_transactionId_fkey] FOREIGN KEY ([transactionId]) REFERENCES [dbo].[GDA_TRANSACTION]([IDGDA_TRANSACTION]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_USERS] ADD CONSTRAINT [GDA_USERS_collaborator_id_fkey] FOREIGN KEY ([collaborator_id]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_FACTOR] ADD CONSTRAINT [GDA_FACTOR_IDGDA_RESULT_fkey] FOREIGN KEY ([IDGDA_RESULT]) REFERENCES [dbo].[GDA_RESULT]([IDGDA_RESULT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_CHECKING_ACCOUNT_IDGDA_CHECKING_ACCOUNT_fkey] FOREIGN KEY ([GDA_CHECKING_ACCOUNT_IDGDA_CHECKING_ACCOUNT]) REFERENCES [dbo].[GDA_CHECKING_ACCOUNT]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_HIERARCHY_IDGDA_HIERARCHY_fkey] FOREIGN KEY ([GDA_HIERARCHY_IDGDA_HIERARCHY]) REFERENCES [dbo].[GDA_HIERARCHY]([IDGDA_HIERARCHY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_INDICATOR_IDGDA_INDICATOR_fkey] FOREIGN KEY ([GDA_INDICATOR_IDGDA_INDICATOR]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_GDA_SECTOR_IDGDA_SECTOR_fkey] FOREIGN KEY ([GDA_SECTOR_IDGDA_SECTOR]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_GDA_PRODUCT_IDGDA_PRODUCT_fkey] FOREIGN KEY ([GDA_PRODUCT_IDGDA_PRODUCT]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_GDA_REASON_REMOVED_IDGDA_REASON_REMOVED_fkey] FOREIGN KEY ([GDA_REASON_REMOVED_IDGDA_REASON_REMOVED]) REFERENCES [dbo].[GDA_REASON_REMOVED]([IDGDA_REASON_REMOVED]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_GDA_STOCK_IDGDA_STOCK_fkey] FOREIGN KEY ([GDA_STOCK_IDGDA_STOCK]) REFERENCES [dbo].[GDA_STOCK]([IDGDA_STOCK]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER_PRODUCT] ADD CONSTRAINT [GDA_ORDER_PRODUCT_GDA_ORDER_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_ORDER_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER_PRODUCT] ADD CONSTRAINT [GDA_ORDER_PRODUCT_GDA_PRODUCT_IDGDA_PRODUCT_fkey] FOREIGN KEY ([GDA_PRODUCT_IDGDA_PRODUCT]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_DELIVERED_BY_fkey] FOREIGN KEY ([DELIVERED_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT_fkey] FOREIGN KEY ([GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT]) REFERENCES [dbo].[GDA_HISTORY_STOCK_PRODUCT]([IDGDA_HISTORY_STOCK_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_GDA_ORDER_STATUS_IDGDA_ORDER_STATUS_fkey] FOREIGN KEY ([GDA_ORDER_STATUS_IDGDA_ORDER_STATUS]) REFERENCES [dbo].[GDA_ORDER_STATUS]([IDGDA_ORDER_STATUS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_ORDER_BY_fkey] FOREIGN KEY ([ORDER_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_RELEASED_BY_fkey] FOREIGN KEY ([RELEASED_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_STOCK_PRODUCT] ADD CONSTRAINT [GDA_STOCK_PRODUCT_GDA_PRODUCT_IDGDA_PRODUCT_fkey] FOREIGN KEY ([GDA_PRODUCT_IDGDA_PRODUCT]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_STOCK_PRODUCT] ADD CONSTRAINT [GDA_STOCK_PRODUCT_GDA_STOCK_IDGDA_STOCK_fkey] FOREIGN KEY ([GDA_STOCK_IDGDA_STOCK]) REFERENCES [dbo].[GDA_STOCK]([IDGDA_STOCK]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_GROUPS] ADD CONSTRAINT [GDA_GROUPS_uploadId_fkey] FOREIGN KEY ([uploadId]) REFERENCES [dbo].[GDA_UPLOADS]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_COLLABORATOR_SECTOR] ADD CONSTRAINT [GDA_HISTORY_COLLABORATOR_SECTOR_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_HIERARCHY_RELATIONSHIP] ADD CONSTRAINT [GDA_HISTORY_HIERARCHY_RELATIONSHIP_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_HIERARCHY_RELATIONSHIP] ADD CONSTRAINT [GDA_HISTORY_HIERARCHY_RELATIONSHIP_IDGDA_HIERARCHY_fkey] FOREIGN KEY ([IDGDA_HIERARCHY]) REFERENCES [dbo].[GDA_HIERARCHY]([IDGDA_HIERARCHY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_HIERARCHY_RELATIONSHIP] ADD CONSTRAINT [GDA_HISTORY_HIERARCHY_RELATIONSHIP_PARENTIDENTIFICATION_fkey] FOREIGN KEY ([PARENTIDENTIFICATION]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_groupId_fkey] FOREIGN KEY ([groupId]) REFERENCES [dbo].[GDA_GROUPS]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_indicator_id_fkey] FOREIGN KEY ([indicator_id]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_GROUP] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_GROUP_sector_id_fkey] FOREIGN KEY ([sector_id]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_ALTERED_BY_fkey] FOREIGN KEY ([ALTERED_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_indicator_id_fkey] FOREIGN KEY ([indicator_id]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_INDICATOR_SECTORS] ADD CONSTRAINT [GDA_HISTORY_INDICATOR_SECTORS_sector_id_fkey] FOREIGN KEY ([sector_id]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_MATHEMATICAL_EXPRESSIONS] ADD CONSTRAINT [GDA_MATHEMATICAL_EXPRESSIONS_indicatorId_fkey] FOREIGN KEY ([indicatorId]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT_IMAGES] ADD CONSTRAINT [GDA_PRODUCT_IMAGES_productId_fkey] FOREIGN KEY ([productId]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT_IMAGES] ADD CONSTRAINT [GDA_PRODUCT_IMAGES_uploadId_fkey] FOREIGN KEY ([uploadId]) REFERENCES [dbo].[GDA_UPLOADS]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCTS] ADD CONSTRAINT [GDA_PRODUCTS_collaboratorId_fkey] FOREIGN KEY ([collaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ADD CONSTRAINT [GDA_PROFILE_PERMISSIONS_permission_id_fkey] FOREIGN KEY ([permission_id]) REFERENCES [dbo].[GDA_PERMISSIONS]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ADD CONSTRAINT [GDA_PROFILE_PERMISSIONS_profile_id_fkey] FOREIGN KEY ([profile_id]) REFERENCES [dbo].[GDA_PROFILES]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PROFILES] ADD CONSTRAINT [GDA_PRFILES_hierarchy_id_fkey] FOREIGN KEY ([hierarchy_id]) REFERENCES [dbo].[GDA_HIERARCHY]([IDGDA_HIERARCHY]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_RESULT] ADD CONSTRAINT [GDA_RESULT_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_RESULT] ADD CONSTRAINT [GDA_RESULT_INDICADORID_fkey] FOREIGN KEY ([INDICADORID]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_RESULT] ADD CONSTRAINT [GDA_RESULT_TRANSACTIONID_fkey] FOREIGN KEY ([TRANSACTIONID]) REFERENCES [dbo].[GDA_TRANSACTION]([IDGDA_TRANSACTION]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_SHOPPING_CART] ADD CONSTRAINT [GDA_SHOPPING_CART_ORDER_BY_fkey] FOREIGN KEY ([ORDER_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_SHOPPING_CART] ADD CONSTRAINT [GDA_SHOPPING_CART_STOCK_PRODUCT_ID_fkey] FOREIGN KEY ([STOCK_PRODUCT_ID]) REFERENCES [dbo].[GDA_STOCK_PRODUCT]([IDGDA_STOCK_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_VISIBILITY] ADD CONSTRAINT [GDA_VISIBILITY_GDA_PRODUCT_IDGDA_PRODUCT_ID_fkey] FOREIGN KEY ([GDA_PRODUCT_IDGDA_PRODUCT_ID]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_VOUCHERS] ADD CONSTRAINT [GDA_VOUCHERS_productId_fkey] FOREIGN KEY ([productId]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
