export const enum Actions {
  Read = 'READ',
  Create = 'CREATE',
  Update = 'UPDATE',
  Delete = 'DELETE',
  FindMany = 'FIND_MANY',
  FindOne = 'FIND_ONE',
  DeleteOne = 'DELET_ONE',
  DeleteMany = 'DELETE_MANY',
  CreatePermission = 'CREATE_PERMISSION',
  UpdatePermission = 'UPDATE_PERMISSION',
  CalculateResultsByTransaction = 'CALCULATE_RESULTS_BY_TRANSACTION',
  FindCheckingAccountCollaborator = 'FIND_CHECKING_ACCOUNT_COLLABORATOR',
  AssociateProductToStock = 'ASSOCIATE_PRODUCT_TO_STOCK',
  FindOwn = 'FIND_OWN',
  ReporStock = 'REPORT_STOCK',
  ConfirmReleasedOrder = 'CONFIRM_RELEASED_ORDER',
  RemoveAssociateSectorsToIndicator = 'REMOVE_ASSOCIATE_SECTORS_TO_INDICATOR',
  ReportMonetizationsByHierarchy = 'REPORT_MONETIZATIONS_BY_HIERARCHY',
  AssociateIndicatorsToSectors = 'ASSOCIATE_INDICATORS_TO_SECTOR',
  ReportSectorsIndicatorsGroups = 'REPORT_SECTORS_INDICATORS_GROUPS',
  InputSectorsIndicatorsGroups = 'INPUT_SECTORS_INDICATORS_GROUPS',
  AddCreditToCollaboratorCheckingAccount = 'ADD_CREDIT_TO_COLLABORATOR_CHECKING_ACCOUNT',
  AddDebtToCollaboratorCheckingAccount = 'ADD_DEBT_TO_COLLABORATOR_CHECKING_ACCOUNT',
  ResetPassword = 'RESET_PASSWORD',
  IndicatorBasketMonetization = 'INDICATOR_BASKET_MONETIZATION',
  GenerateQrCodeOrder = 'GENERATE_QRCODE_ORDER',
}
