export enum RemoveReason {
  'SOLD' = 'SOLD',
  'EXPIRED' = 'EXPIRED',
  'OTHER' = 'OTHER',
  'STARTED' = 'STARTED',
  'INSERT_PRODUCT' = 'INSERT PRODUCT',
  'TRANSFERRED' = 'TRANSFERRED',
  'INSERT_QUANTITY_PRODUCT' = 'INSERT QUANTITY PRODUCT',
  'QRCODE' = 'QRCODE',
  'ORDER' = 'ORDER',
  'CANCELED' = 'CANCELED',
  'REMOVAL' = 'REMOVAL',
}
