BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_COLLABORATOR_ACTIVE] (
    [IDGDA_HIERARCHY] INT NOT NULL IDENTITY(1,1),
    [IDGDA_COLLABORATORS] INT NOT NULL,
    [ENTRYDATE] INT NOT NULL,
    [ACTIVE] INT NOT NULL,
    [TRANSACTIONID] INT NOT NULL,
    CONSTRAINT [GDA_HISTORY_COLLABORATOR_ACTIVE_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HIERARCHY])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_COLLABORATOR_ACTIVE] ADD CONSTRAINT [GDA_HISTORY_COLLABORATOR_ACTIVE_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
