/*
  Warnings:

  - You are about to drop the column `GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT` on the `GDA_ORDER` table. All the data in the column will be lost.

*/
BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[GDA_ORDER] DROP CONSTRAINT [GDA_ORDER_GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT_fkey];

-- AlterTable
ALTER TABLE [dbo].[GDA_ORDER] DROP COLUMN [GDA_HISTORY_STOCK_PRODUCT_IDGDA_HISTORY_STOCK_PRODUCT];

-- AlterTable
ALTER TABLE [dbo].[GDA_PRODUCT] ADD [COMERCIAL_NAME] NVARCHAR(1000),
[EXPIRATION_DATE] DATETIME2,
[GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS] INT,
[HIGHLIGHT] INT NOT NULL CONSTRAINT [GDA_PRODUCT_HIGHLIGHT_df] DEFAULT 0,
[PUBLICATION_DATE] DATETIME2,
[UPDATED_AT] DATETIME2;

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_PRODUCT] (
    [IDGDA_PRODUCT] INT NOT NULL IDENTITY(1,1),
    [GDA_PRODUCT_IDGDA_PRODUCT] INT,
    [GDA_ORDER_IDGDA_ORDER] INT,
    [GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS] INT,
    [UPDATED_AT] DATETIME2,
    [GDA_COLLABORATOR_IDGDA_COLLABORATORS] INT,
    [DESCRIPTION] NVARCHAR(1000) NOT NULL,
    [price] FLOAT(53) NOT NULL,
    [HIGHLIGHT] INT NOT NULL CONSTRAINT [GDA_HISTORY_PRODUCT_HIGHLIGHT_df] DEFAULT 0,
    [PUBLICATION_DATE] DATETIME2,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_PRODUCT_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_HISTORY_PRODUCT_pkey] PRIMARY KEY CLUSTERED ([IDGDA_PRODUCT])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_PRODUCT_STATUS] (
    [IDGDA_PRODUCT_STATUS] INT NOT NULL IDENTITY(1,1),
    [STATUS] NVARCHAR(1000),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_PRODUCT_STATUS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [GDA_PRODUCT_STATUS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_PRODUCT_STATUS])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT] ADD CONSTRAINT [GDA_PRODUCT_GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS_fkey] FOREIGN KEY ([GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS]) REFERENCES [dbo].[GDA_PRODUCT_STATUS]([IDGDA_PRODUCT_STATUS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_PRODUCT_GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS_fkey] FOREIGN KEY ([GDA_PRODUCT_STATUS_IDGDA_PRODUCT_STATUS]) REFERENCES [dbo].[GDA_PRODUCT_STATUS]([IDGDA_PRODUCT_STATUS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_PRODUCT_GDA_PRODUCT_IDGDA_PRODUCT_fkey] FOREIGN KEY ([GDA_PRODUCT_IDGDA_PRODUCT]) REFERENCES [dbo].[GDA_PRODUCT]([IDGDA_PRODUCT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_PRODUCT_GDA_ORDER_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_ORDER_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_PRODUCT_GDA_COLLABORATOR_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([GDA_COLLABORATOR_IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
