BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_STOCK] ADD [GDA_ATRIBUTES] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_STOCK_GDA_ATRIBUTES_df] DEFAULT '',
[campaign] NVARCHAR(1000) NOT NULL CONSTRAINT [GDA_STOCK_campaign_df] DEFAULT '';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
