BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD [WEIGHT] INT CONSTRAINT [GDA_CHECKING_ACCOUNT_WEIGHT_df] DEFAULT 1;

-- AlterTable
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD [WEIGHT] INT CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_WEIGHT_df] DEFAULT 1;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
