BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION] (
    [IDGDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_RELATIONSHIP] INT NOT NULL IDENTITY(1,1),
    [PARENTIDENTIFICATION] INT NOT NULL,
    [IDGDA_COLLABORATORS] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [DATE] DATETIME2,
    CONSTRAINT [GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_RELATIONSHIP])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_IDGDA_COLLABORATORS_PARENTIDENTIFICATION_idx] ON [dbo].[GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION]([IDGDA_COLLABORATORS], [PARENTIDENTIFICATION]);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION] ADD CONSTRAINT [GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_IDGDA_COLLABORATORS_fkey] FOREIGN KEY ([IDGDA_COLLABORATORS]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION] ADD CONSTRAINT [GDA_HISTORY_PROFILE_COLLABORATOR_ADMINISTRATION_PARENTIDENTIFICATION_fkey] FOREIGN KEY ([PARENTIDENTIFICATION]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
