BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD [createdByCollaboratorId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_createdByCollaboratorId_fkey] FOREIGN KEY ([createdByCollaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
