import * as process from 'process';
import {
  API_PORT,
  API_HOST,
  API_PROTOCOL,
  DATABASE_CONNECTION,
  JWT_SECRET,
  URL_API,
  AZURE_STORAGE_CONNECTION_STRING,
  AZURE_CONTAINER_NAME,
} from './environment-variable.constants';

export const env = {
  JWT_SECRET: JWT_SECRET,
  APP_VERSION: process.env.npm_package_version,
  API_HOST: API_HOST,
  API_PORT: API_PORT,
  API_PROTOCOL: API_PROTOCOL,
  DATABASE_URL: DATABASE_CONNECTION,
  URL_API: URL_API,
  AZURE_STORAGE_CONNECTION_STRING: AZURE_STORAGE_CONNECTION_STRING,
  AZURE_CONTAINER_NAME: AZURE_CONTAINER_NAME,
};
