BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_ORDER] ADD [LAST_UPDATED_AT] DATETIME2,
[LAST_UPDATED_BY] INT;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER] ADD CONSTRAINT [GDA_ORDER_LAST_UPDATED_BY_fkey] FOREIGN KEY ([LAST_UPDATED_BY]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
