BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD [REASON_COMMENT] NVARCHAR(1000);

-- AlterTable
ALTER TABLE [dbo].[GDA_PRODUCT] ADD [GDA_GROUP_IDGDA_GROUP] INT;

-- AlterTable
ALTER TABLE [dbo].[GDA_SECTOR] ADD [SECTOR] INT;

-- CreateTable
CREATE TABLE [dbo].[GDA_PRODUCT_GROUP] (
    [IDGDA_PRODUCT_GROUP] INT NOT NULL IDENTITY(1,1),
    [PRODUCT_GROUP_NAME] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_PRODUCT_GROUP_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [createdByCollaboratorId] INT NOT NULL,
    CONSTRAINT [GDA_PRODUCT_GROUP_pkey] PRIMARY KEY CLUSTERED ([IDGDA_PRODUCT_GROUP])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_COLLABORATOR_VOUCHER] ADD CONSTRAINT [GDA_COLLABORATOR_VOUCHER_GDA_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT] ADD CONSTRAINT [GDA_PRODUCT_GDA_GROUP_IDGDA_GROUP_fkey] FOREIGN KEY ([GDA_GROUP_IDGDA_GROUP]) REFERENCES [dbo].[GDA_PRODUCT_GROUP]([IDGDA_PRODUCT_GROUP]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT_GROUP] ADD CONSTRAINT [GDA_PRODUCT_GROUP_createdByCollaboratorId_fkey] FOREIGN KEY ([createdByCollaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
