import { defineAbility } from "@casl/ability";

const listOfPermissions = [
  {
    id: 1,
    action: "Ver Ranking",
    resource: "Home",
    active: true,
  },
  {
    id: 2,
    action: "Ver resultado de todos os setores",
    resource: "Home",
    active: true,
  },
  {
    id: 3,
    action: "Ver Grupos",
    resource: "Grupos",
    active: false,
  },
  {
    id: 4,
    action: "Editar Grupos",
    resource: "Grupos",
    active: false,
  },
  {
    id: 5,
    action: "Ver Setores",
    resource: "Setores",
    active: true,
  },
  {
    id: 6,
    action: "Editar Setores",
    resource: "Setores",
    active: true,
  },
  {
    id: 7,
    action: "Ver Indicadores",
    resource: "Indicadores",
    active: true,
  },
  {
    id: 8,
    action: "Editar Indicadores",
    resource: "Indicadores",
    active: true,
  },
  {
    id: 9,
    action: "Ver Metricas",
    resource: "Metricas",
    active: true,
  },
  {
    id: 10,
    action: "Editar Metricas",
    resource: "Metricas",
    active: true,
  },
  {
    id: 11,
    action: "Ver Perfis",
    resource: "Perfis",
    active: true,
  },
  {
    id: 12,
    action: "Editar Perfis",
    resource: "Perfis",
    active: true,
  },
  {
    id: 13,
    action: "Ver Colaboradores",
    resource: "Perfis",
    active: true,
  },
  {
    id: 14,
    action: "Editar Colaboradores",
    resource: "Perfis",
    active: true,
  },
  {
    id: 15,
    action: "Ver Permissões",
    resource: "Perfis",
    active: true,
  },
  {
    id: 16,
    action: "Editar Permissões",
    resource: "Perfis",
    active: true,
  },
  {
    id: 17,
    action: "Extrato da conta",
    resource: "Monetização",
    active: true,
  },
  {
    id: 18,
    action: "Adicionar Creditos a um colaborador",
    resource: "Monetização",
    active: true,
  },
  {
    id: 19,
    action: "Ver Loja",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 20,
    action: "Ver Meus Pedidos",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 21,
    action: "Ver Meus Vouchers",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 22,
    action: "Ver Produto",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 23,
    action: "Relatorio de Monetização",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 24,
    action: "Cadastrar Produto",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 25,
    action: "Ver Voucher",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 26,
    action: "Editar Voucher",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 27,
    action: "Cadastrar Voucher",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 28,
    action: "Ver Estoque",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 29,
    action: "Editar Estoque",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 30,
    action: "Ver administrar Pedidos",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 31,
    action: "Editar administrar Pedidos",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 32,
    action: "Ver Configurar Vitrine",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 33,
    action: "Editar Configurar vitrine",
    resource: "Marketing Place",
    active: true,
  },
  {
    id: 34,
    action: "Relatorio de monetização",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 35,
    action: "Relatorio de estoque",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 36,
    action: "Relatorios de estoque - padrão",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 37,
    action: "Relatorios de estoque - gerenciar estoque",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 38,
    action: "Relatorios de estoque - entrada voucher",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 39,
    action: "Relatorios de estoque - saida voucher",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 40,
    action: "Relatorios de estoque - movimentação",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 41,
    action: "Relatorio de pedidos",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 45,
    action: "Relatorio de resultados",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 46,
    action: "Configurar Cesta de Indicadores",
    resource: "Indicadores",
    active: true,
  },
  {
    id: 47,
    action: "Ver Cesta de Indicadores",
    resource: "Indicadores",
    active: true,
  },
  {
    id: 48,
    action: "Ver produtos independente da cesta de indicadores",
    resource: "Marketing Place",
    active: false,
  },
  {
    id: 49,
    action: "Ver resultados de indicadores sem meta",
    resource: "Home",
    active: false,
  },
  {
    id: 50,
    action: "Editar Hobby",
    resource: "Persona",
    active: false,
  },
  {
    id: 51,
    action: "Editar Persona ADM",
    resource: "Persona",
    active: false,
  },
  {
    id: 52,
    action: "Editar Blacklist",
    resource: "Persona",
    active: false,
  },
  {
    id: 53,
    action: "Criar Publicação",
    resource: "Persona",
    active: true,
  },
  {
    id: 54,
    action: "Relatorio de tempo logado",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 55,
    action: "Configuração Publico e Privado",
    resource: "Persona",
    active: true,
  },
  /* {
        id: 56,
        action: "Limpar Notificacao",
        resource: "Notificacao",
        active: true,
    }, */
  /* {
        id: 57,
        action: "Editar Notificacao",
        resource: "Notificacao",
        active: true,
    }, */
  /* {
        id: 58,
        action: "Enviar Notificacao",
        resource: "Notificacao",
        active: true,
    }, */
  {
    id: 59,
    action: "Config Expiração Moedas",
    resource: "Expiração Moedas",
    active: true,
  },
  {
    id: 60,
    action: "Criar conta comercial",
    resource: "Persona",
    active: true,
  },
  {
    id: 61,
    action: "Gerenciar Quiz",
    resource: "Quiz",
    active: true,
  },
  {
    id: 62,
    action: "Gerenciar Notificacoes",
    resource: "Notificacao",
    active: true,
  },
  {
    id: 63,
    action: "Ver Clima",
    resource: "Clima",
    active: true,
  },
  {
    id: 64,
    action: "Gerenciar Feedback",
    resource: "Feedback",
    active: true,
  },
  {
    id: 65,
    action: "Relatorio Feedback",
    resource: "Feedback",
    active: true,
  },
  {
    id: 66,
    action: "Gerenciar Campanha",
    resource: "Campanha Operacional",
    active: true,
  },/* 
  {
    id: 67,
    action: "Relatorio Campanha",
    resource: "Campanha Operacional",
    active: true,
  }, */
  {
    id: 68,
    action: "Ver Escalation",
    resource: "Escalation",
    active: true,
  },
  {
    id: 69,
    action: "Criar Ação automatica",
    resource: "Escalation",
    active: true,
  },
  {
    id: 70,
    action: "Criar Stage",
    resource: "Escalation",
    active: true,
  },  
  {
    id: 71,
    action: "Criar Plano de ação",
    resource: "Escalation",
    active: true,
  },  
  {
    id: 72,
    action: "Relatorio de plano de ação",
    resource: "Relatorios",
    active: true,
  },  
  {
    id: 73,
    action: "Relatorio de notificação",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 74,
    action: "Trocar persona",
    resource: "Persona",
    active: true,
  },
  {
    id: 75,
    action: "Meus Quizzes",
    resource: "Quiz",
    active: true,
  },
  {
    id: 76,
    action: "Meus Feedbacks",
    resource: "Feedback",
    active: true,
  },
  {
    id: 77,
    action: "Relatorio de setores",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 78,
    action: "Relatorio geral de estoque",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 79,
    action: "Relatorio de fechamento de caixa",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 80,
    action: "Relatorio de quiz",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 81,
    action: "Relatorio de campanha",
    resource: "Relatorios",
    active: true,
  },
  {
    id: 82,
    action: "Visibilidade Publicação",
    resource: "Persona",
    active: true,
  },
  {
    id: 83,
    action: "Painel de integração",
    resource: "Painel",
    active: true,
  },
  {
    id: 84,
    action: "Painel de verificação",
    resource: "Painel",
    active: true,
  },
];

export default (permissions: number[]) =>
  defineAbility((can) => {
    listOfPermissions.map((item) => {
      permissions.includes(item.id) && can(item.action, item.resource);
    });
  });
