BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] DROP CONSTRAINT [GDA_CHECKING_ACCOUNT_collaborator_id_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] DROP CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_INDICATOR_IDGDA_INDICATOR_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] DROP CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_ORDER_IDGDA_ORDER_fkey];

-- AlterTable
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD [IDGDA_RESULT] INT,
[RESULT_DATE] DATETIME2;

-- AlterTable
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD [IDGDA_RESULT] INT,
[RESULT_DATE] DATETIME2;

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] (
    [id] INT NOT NULL IDENTITY(1,1),
    [RESULT_DATE] DATETIME2,
    [MONETIZATION_DATE] DATETIME2,
    [IDGDA_RESULT] INT,
    [IDGDA_COLLABORATOR] INT,
    [IDGDA_INDICATOR] INT,
    [IDGDA_SECTOR] INT,
    [IDGDA_HIERARCHY] INT,
    [MONETIZATION] FLOAT(53),
    [BEFORE_MONETIZATION] FLOAT(53),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2 CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_DELETED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_collaborator_id_fkey] FOREIGN KEY ([collaborator_id]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_INDICATOR_IDGDA_INDICATOR_fkey] FOREIGN KEY ([GDA_INDICATOR_IDGDA_INDICATOR]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_GDA_ORDER_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_ORDER_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CHECKING_ACCOUNT_IDGDA_RESULT_fkey] FOREIGN KEY ([IDGDA_RESULT]) REFERENCES [dbo].[GDA_RESULT]([IDGDA_RESULT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CONSOLIDATE_CHECKING_ACCOUNT] ADD CONSTRAINT [GDA_CONSOLIDATE_CHECKING_ACCOUNT_IDGDA_RESULT_fkey] FOREIGN KEY ([IDGDA_RESULT]) REFERENCES [dbo].[GDA_RESULT]([IDGDA_RESULT]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_RESULT_fkey] FOREIGN KEY ([IDGDA_RESULT]) REFERENCES [dbo].[GDA_RESULT]([IDGDA_RESULT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_COLLABORATOR_fkey] FOREIGN KEY ([IDGDA_COLLABORATOR]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_INDICATOR_fkey] FOREIGN KEY ([IDGDA_INDICATOR]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_SECTOR_fkey] FOREIGN KEY ([IDGDA_SECTOR]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MONETIZATION_RECALCULATION] ADD CONSTRAINT [GDA_HISTORY_MONETIZATION_RECALCULATION_IDGDA_HIERARCHY_fkey] FOREIGN KEY ([IDGDA_HIERARCHY]) REFERENCES [dbo].[GDA_HIERARCHY]([IDGDA_HIERARCHY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
