/*
  Warnings:

  - You are about to drop the column `indicatorId` on the `GDA_MATHEMATICAL_EXPRESSIONS` table. All the data in the column will be lost.

*/
BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[GDA_MATHEMATICAL_EXPRESSIONS] DROP CONSTRAINT [GDA_MATHEMATICAL_EXPRESSIONS_indicatorId_fkey];

-- AlterTable
ALTER TABLE [dbo].[GDA_MATHEMATICAL_EXPRESSIONS] DROP COLUMN [indicatorId];

-- CreateTable
CREATE TABLE [dbo].[GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR] (
    [id] INT NOT NULL IDENTITY(1,1),
    [mathematicalExpressionId] INT NOT NULL,
    [indicatorId] INT NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR] ADD CONSTRAINT [GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR_indicatorId_fkey] FOREIGN KEY ([indicatorId]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR] ADD CONSTRAINT [GDA_HISTORY_MATHEMATICAL_EXPRESSIONS_INDICATOR_mathematicalExpressionId_fkey] FOREIGN KEY ([mathematicalExpressionId]) REFERENCES [dbo].[GDA_MATHEMATICAL_EXPRESSIONS]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
