BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] DROP CONSTRAINT [GDA_PROFILE_PERMISSIONS_profile_id_fkey];

-- AlterTable
ALTER TABLE [dbo].[GDA_COLLABORATORS] ADD [PROFILE_COLLABORATOR_ADMINISTRATIONID] INT;

-- AlterTable
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ALTER COLUMN [profile_id] INT NULL;
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ADD [profile_collaborator_administration_id] INT;

-- CreateTable
CREATE TABLE [dbo].[GDA_PROFILE_COLLABORATOR_ADMINISTRATION] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [GDA_PROFILE_COLLABORATOR_ADMINISTRATION_reated_at_df] DEFAULT CURRENT_TIMESTAMP,
    [deleted_at] DATETIME2,
    CONSTRAINT [GDA_PROFILE_COLLABORATOR_ADMINISTRATION_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_COLLABORATORS] ADD CONSTRAINT [GDA_COLLABORATORS_PROFILE_COLLABORATOR_ADMINISTRATIONID_fkey] FOREIGN KEY ([PROFILE_COLLABORATOR_ADMINISTRATIONID]) REFERENCES [dbo].[GDA_PROFILE_COLLABORATOR_ADMINISTRATION]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ADD CONSTRAINT [GDA_PROFILE_PERMISSIONS_profile_id_fkey] FOREIGN KEY ([profile_id]) REFERENCES [dbo].[GDA_PROFILES]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PROFILE_PERMISSIONS] ADD CONSTRAINT [GDA_PROFILE_PERMISSIONS_profile_collaborator_administration_id_fkey] FOREIGN KEY ([profile_collaborator_administration_id]) REFERENCES [dbo].[GDA_PROFILE_COLLABORATOR_ADMINISTRATION]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
