BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_HISTORY_COLLABORATOR_SECTOR] ADD [DELETED_AT] DATETIME2;

-- AlterTable
ALTER TABLE [dbo].[GDA_INDICATOR] ADD [TYPE] NVARCHAR(1000);

-- AlterTable
ALTER TABLE [dbo].[GDA_RESULT] ADD [DELETED_AT] DATETIME2;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
