/*
  Warnings:

  - Added the required column `GDA_IDGDA_ORDER` to the `GDA_COLLABORATOR_VOUCHER` table without a default value. This is not possible if the table is not empty.

*/
BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_VOUCHERS] ADD [stockId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_COLLABORATOR_VOUCHER] ADD CONSTRAINT [GDA_COLLABORATOR_VOUCHER_GDA_IDGDA_ORDER_fkey] FOREIGN KEY ([GDA_IDGDA_ORDER]) REFERENCES [dbo].[GDA_ORDER]([IDGDA_ORDER]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_VOUCHERS] ADD CONSTRAINT [GDA_VOUCHERS_stockId_fkey] FOREIGN KEY ([stockId]) REFERENCES [dbo].[GDA_STOCK]([IDGDA_STOCK]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
