BEGIN TRY

BEGIN TRAN;


-- CreateTable
CREATE TABLE [dbo].[GDA_HOLIDAYS] (
    [IDGDA_HOLIDAY] INT NOT NULL IDENTITY(1,1),
    [HOLYDAY_DATE] NVARCHAR(1000) NOT NULL,
    [SITE] NVARCHAR(1000) NOT NULL,
    [TYPE] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_HOLIDAYS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [createdByCollaboratorId] INT NOT NULL,
    CONSTRAINT [GDA_HOLIDAYS_pkey] PRIMARY KEY CLUSTERED ([IDGDA_HOLIDAY])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HOLIDAYS] ADD CONSTRAINT [GDA_HOLIDAYS_createdByCollaboratorId_fkey] FOREIGN KEY ([createdByCollaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
