BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD [GDA_SUPPLIER_IDGDA_SUPPLIER] INT;

-- AlterTable
ALTER TABLE [dbo].[GDA_ORDER_PRODUCT] ADD [GDA_SUPPLIER_IDGDA_SUPPLIER] INT;

-- AlterTable
ALTER TABLE [dbo].[GDA_PRODUCT] ADD [GDA_CATEGORY_IDGDA_CATEGORY] INT;

-- AlterTable
ALTER TABLE [dbo].[GDA_STOCK_PRODUCT] ADD [GDA_SUPPLIER_IDGDA_SUPPLIER] INT;

-- CreateTable
CREATE TABLE [dbo].[GDA_SUPPLIER] (
    [IDGDA_SUPPLIER] INT NOT NULL IDENTITY(1,1),
    [SUPPLIER_NAME] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_SUPPLIER_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [createdByCollaboratorId] INT NOT NULL,
    CONSTRAINT [GDA_SUPPLIER_pkey] PRIMARY KEY CLUSTERED ([IDGDA_SUPPLIER])
);

-- CreateTable
CREATE TABLE [dbo].[GDA_CATEGORIES] (
    [IDGDA_CATEGORY] INT NOT NULL IDENTITY(1,1),
    [CATEGORY_NAME] NVARCHAR(1000) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_CATEGORIES_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [DELETED_AT] DATETIME2,
    [createdByCollaboratorId] INT NOT NULL,
    CONSTRAINT [GDA_CATEGORIES_pkey] PRIMARY KEY CLUSTERED ([IDGDA_CATEGORY])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_HISTORY_STOCK_PRODUCT] ADD CONSTRAINT [GDA_HISTORY_STOCK_PRODUCT_GDA_SUPPLIER_IDGDA_SUPPLIER_fkey] FOREIGN KEY ([GDA_SUPPLIER_IDGDA_SUPPLIER]) REFERENCES [dbo].[GDA_SUPPLIER]([IDGDA_SUPPLIER]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_ORDER_PRODUCT] ADD CONSTRAINT [GDA_ORDER_PRODUCT_GDA_SUPPLIER_IDGDA_SUPPLIER_fkey] FOREIGN KEY ([GDA_SUPPLIER_IDGDA_SUPPLIER]) REFERENCES [dbo].[GDA_SUPPLIER]([IDGDA_SUPPLIER]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_PRODUCT] ADD CONSTRAINT [GDA_PRODUCT_GDA_CATEGORY_IDGDA_CATEGORY_fkey] FOREIGN KEY ([GDA_CATEGORY_IDGDA_CATEGORY]) REFERENCES [dbo].[GDA_CATEGORIES]([IDGDA_CATEGORY]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_STOCK_PRODUCT] ADD CONSTRAINT [GDA_STOCK_PRODUCT_GDA_SUPPLIER_IDGDA_SUPPLIER_fkey] FOREIGN KEY ([GDA_SUPPLIER_IDGDA_SUPPLIER]) REFERENCES [dbo].[GDA_SUPPLIER]([IDGDA_SUPPLIER]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_SUPPLIER] ADD CONSTRAINT [GDA_SUPPLIER_createdByCollaboratorId_fkey] FOREIGN KEY ([createdByCollaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_CATEGORIES] ADD CONSTRAINT [GDA_CATEGORIES_createdByCollaboratorId_fkey] FOREIGN KEY ([createdByCollaboratorId]) REFERENCES [dbo].[GDA_COLLABORATORS]([IDGDA_COLLABORATORS]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
