BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[GDA_BASKET_INDICATOR] (
    [IDGDA_BASKET_INDICATOR] INT NOT NULL IDENTITY(1,1),
    [SECTOR_ID] INT NOT NULL,
    [INDICATOR_ID] INT NOT NULL,
    [DATE] DATETIME2 NOT NULL CONSTRAINT [GDA_BASKET_INDICATOR_DATE_df] DEFAULT CURRENT_TIMESTAMP,
    [WEIGHT] INT CONSTRAINT [GDA_BASKET_INDICATOR_WEIGHT_df] DEFAULT 1,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [GDA_BASKET_INDICATOR_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [GDA_BASKET_INDICATOR_pkey] PRIMARY KEY CLUSTERED ([IDGDA_BASKET_INDICATOR])
);

-- AddForeignKey
ALTER TABLE [dbo].[GDA_BASKET_INDICATOR] ADD CONSTRAINT [GDA_BASKET_INDICATOR_SECTOR_ID_fkey] FOREIGN KEY ([SECTOR_ID]) REFERENCES [dbo].[GDA_SECTOR]([IDGDA_SECTOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[GDA_BASKET_INDICATOR] ADD CONSTRAINT [GDA_BASKET_INDICATOR_INDICATOR_ID_fkey] FOREIGN KEY ([INDICATOR_ID]) REFERENCES [dbo].[GDA_INDICATOR]([IDGDA_INDICATOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
